services:
  backend:
    build:
      context: ./src          # üîπ build context src ‡¶´‡ßã‡¶≤‡ßç‡¶°‡¶æ‡¶∞
      dockerfile: Dockerfile  # üîπ Dockerfile ‡¶ì src ‡¶§‡ßá‡¶á ‡¶Ü‡¶õ‡ßá
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app            # üîπ Local src ‡¶Æ‡¶æ‡¶â‡¶®‡ßç‡¶ü ‡¶ï‡¶∞‡ßá ‡¶¶‡¶ø‡¶ö‡ßç‡¶õ‡¶ø
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: fakesongdetection-db-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fakesongdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
